name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: FlowDots
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Deploy via SSH and Rsync
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22  # Change this if your SSH server uses a custom port
        script: |
          rsync -avz --delete ./ /opt/infra-saas/landing/flowdots-landing
